apiVersion: v1
kind: ConfigMap
metadata:
  name: gitops-settings
  namespace: gitops-demo
data:
  apiImage: "863518411441.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo-api:latest"
  workerImage: "863518411441.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo-worker:latest"
  migratorImage: "863518411441.dkr.ecr.ap-south-1.amazonaws.com/gitops-demo-migrator:latest"
  apiRoleArn: "arn:aws:iam::863518411441:role/gitops-demo-api-irsa"
  workerRoleArn: "arn:aws:iam::863518411441:role/gitops-demo-worker-irsa"
  apiHost: "api.example.com"