apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: gitops-demo
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
