apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: gitops-demo
spec:
  template:
    metadata:
      annotations:
        lesson.gitops/demo-ts: "2026-06-25-0438"
      labels:
        observability: enabled
    spec:
      containers:
        - name: api
          env:
            - name: DEPLOY_ENV
              value: "eks"
            - name: OTEL_SERVICE_NAME
              value: "gitops-demo-api"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.observability.svc.cluster.local:4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=gitops-demo,deployment.environment=eks"