apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api
  namespace: gitops-demo
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api
  namespaceSelector:
    matchNames:
      - gitops-demo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
