apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-sa
  namespace: gitops-demo
  annotations:
    eks.amazonaws.com/role-arn: "replace-me"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker-sa
  namespace: gitops-demo
  annotations:
    eks.amazonaws.com/role-arn: "replace-me"
