apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-secret
  namespace: gitops-demo
spec:
  secretStoreRef:
    name: aws-store
    kind: SecretStore
  target:
    name: app-secret
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: gitops-demo/database
        property: password
